version: '3.3'

services:
  php:
    build:
      context: ./docker/php
    expose:
      - 9000
    network_mode: bridge
    restart: always
    user: 1000:1000
    volumes:
      - ./docker/php/custom.ini://usr/local/etc/php/conf.d/custom.ini:rw
      - .:/var/www/app/www:rw
    working_dir: /var/www/app/www
  nginx:
    build:
      context: ./docker/nginx
    environment:
      VIRTUAL_HOST: my.md
    expose:
    - 80
    links:
    - php
    network_mode: bridge
    restart: always
    volumes:
    - .:/var/www/app/www:rw



